<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-J1J1V9M" failures="1" tests="6" name="TestNGd_FailedTestCases.A_FailedTestCases" time="0.074" errors="0" timestamp="2022-11-25T11:09:13 GMT-05:00" skipped="0">
  <testcase classname="TestNGd_FailedTestCases.A_FailedTestCases" name="Tc2" time="0.008"/>
  <system-out>
    <![CDATA[Running Tc2]]>
  </system-out>
  <testcase classname="TestNGd_FailedTestCases.A_FailedTestCases" name="Tc3" time="0.003"/>
  <system-out>
    <![CDATA[Running Tc3]]>
  </system-out>
  <testcase classname="TestNGd_FailedTestCases.A_FailedTestCases" name="Tc6" time="0.011"/>
  <system-out>
    <![CDATA[Running Tc6]]>
  </system-out>
  <testcase classname="TestNGd_FailedTestCases.A_FailedTestCases" name="Tc1" time="0.036"/>
  <system-out>
    <![CDATA[Running Tc1]]>
  </system-out>
  <testcase classname="TestNGd_FailedTestCases.A_FailedTestCases" name="Tc5" time="0.009"/>
  <system-out>
    <![CDATA[Running Tc5]]>
  </system-out>
  <testcase classname="TestNGd_FailedTestCases.A_FailedTestCases" name="Tc4" time="0.007">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at TestNGd_FailedTestCases.A_FailedTestCases.Tc4(A_FailedTestCases.java:26)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Tc4 -->
  <system-out/>
</testsuite> <!-- TestNGd_FailedTestCases.A_FailedTestCases -->
